# ----------------------------------------------------------------------------------
# Project: BeamtimeApp
# File: .pre-commit-config.yaml
# ----------------------------------------------------------------------------------
# Purpose:
# This file is used to configure the pre-commit hooks that will be used to check
# the code before it is committed to the repository.
# ----------------------------------------------------------------------------------
# Author: Christofanis Skordas
#
# Copyright (C) 2025 GSECARS, The University of Chicago, USA
# Copyright (C) 2025 NSF SEES, USA
# ----------------------------------------------------------------------------------

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: ["Flake8-pyproject"]