# ----------------------------------------------------------------------------------
# Project: BeamtimeApp
# File: .pre-commit-config.yaml
# ----------------------------------------------------------------------------------
# Purpose:
# This file is used to configure the pre-commit hooks that will be used to check
# the code before it is committed to the repository.
# ----------------------------------------------------------------------------------
# Author: Christofanis Skordas
#
# Copyright (C) 2025 GSECARS, The University of Chicago, USA
# Copyright (C) 2025 NSF SEES, USA
# ----------------------------------------------------------------------------------

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.13
    hooks:
      - id: uv-lock